default_language_version:
  python: python3.9

default_stages: [commit, push]

repos:
  - repo: local
    hooks:
      - id: isort
        name: isort
        entry: isort
        types: [python]
        language: system
        args: ["--profile", "black"]

      - id: black
        name: black
        entry: black
        types: [python]
        language: system

      - id: flake8
        name: flake8
        entry: flake8 --max-line-length=88 --extend-ignore=E203
        types: [python]
        language: system

      - id: bandit
        name: bandit
        entry: bandit -x tests/
        types: [python]
        language: system
