version: "3.8"

services:
  api:
    build: .
    command: uvicorn tft_stats.main:app --reload --host 0.0.0.0 --port 8000
    environment:
      - DEBUG=True
    ports:
      - '8000:8000'
    volumes:
      - ./:/usr/src/app
